### ISSUE TITLE
How could I get the framework file in "../../../../../usr/local/Frameworks/Python.framework"?

### ISSUE THREAD

**Issue by JohnAizb** [pvieito/PythonKit#4]
in PythonKit.xcodeproj  -> project.pbxproj
		AAE9EBB0211F0DAF00B0EE03 /* Python.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = Python.framework; path = ../../../../../usr/local/Frameworks/Python.framework; sourceTree = "<group>"; }; 

How could I get the framework file in "../../../../../usr/local/Frameworks/Python.framework"?

**Comment by pvieito** [comment]
The new design of PythonKit links to Python at runtime so that it is no longer needed. I have updated the repo with that reference removed.
