### ISSUE TITLE
Is there a way that I can have a callback function defined in Swift and called in Python?

### ISSUE THREAD

**Issue by JohnAizb** [pvieito/PythonKit#5]
May I have a way to get a callback function defined in Swift and called in Python?

Py_InitModule haven't get implemented in PythonKit yet.

**Comment by pvieito** [comment]
Hi! PythonKit is a Swift PM wrapper with dynamic linking around the Python interop layer implemented as part as the [Swift for TensorFlow](https://github.com/tensorflow/swift) project. 

Questions, issues or features about the interop layer itself should be asked there. Thanks!
