### ISSUE TITLE
error: unknown attribute 'dynamicCallable'

### ISSUE THREAD

**Issue by flvckx** [pvieito/PythonKit#6]
I run 'swift build' command and there's a bunch of errors.. including this one 

`error: unknown attribute 'dynamicCallable'`

I'm new to swift PM, so prolly I messed up on something 😶

**Comment by pvieito** [comment]
PythonKit requires Swift 5, you can get a Trunk Development toolchain from [swift.org](https://swift.org/download/#snapshots).
