### ISSUE TITLE
Dictionary conversion EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by walwe** [pvieito/PythonKit#9]
I came across a memory access problem parsing a nested dictionary twice .
The following results in: EXC_BAD_ACCESS
```
import PythonKit

let json = Python.import("json")
let j = json.loads("{\"a\": {\"aa\": \"AA\"}}")

print([String: [String: String]](j))
print([String: PythonObject](j))
```
Whats wrong here?

Thanks!

**Comment by pvieito** [comment]
@walwe Hi! You can ask questions about the Python interoperability layer in the [Swift for TensorFlow](https://groups.google.com/a/tensorflow.org/forum/#!forum/swift) mailing list.

PythonKit is a Swift package which allows to use the Python interoperability layer from the Swift for TensorFlow project with the standard Swift distribution.
